import { Color } from '../../assets'
import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container : {
    flexDirection: 'row',
  },
  shimmerStory : {
    padding: 15,
    width: 'auto',
    height: 'auto',
    borderWidth : 0,
    borderRadius: 20,
  },
  shimmerPromo : {
    height: 100,
    borderWidth: 0,
    borderRadius: 20,
    maxWidth: '100%',
    borderColor: Color.transparent,
    backgroundColor: Color.greyMedium,
  },
  shimmerCategory : {
    width: 70,
    marginTop: 4,
    borderRadius: 14,
    paddingVertical: 13,
    marginHorizontal: 4,
    paddingHorizontal: 18,
    backgroundColor: 'red',
  },
  shimmerClass : { flex:1,
    height: 210,
    width: '100%',
    borderWidth: 0,
    borderRadius: 20,
    alignSelf:'center',
    marginVertical :10,
    shadowColor: '#000',
    borderColor: '#dddddd',
    backgroundColor: Color.white
  },
  shimmerClass1 : {
    height: 120,
    borderWidth: 0,
    maxWidth: '100%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderColor: Color.transparent,
    backgroundColor: Color.greyMedium,
  },
  shimmerClass2 : {
    height: 10,
    marginTop: 8,
    borderWidth: 0,
    borderRadius: 5,
    marginHorizontal: '3%',
    borderColor: Color.transparent,
  },
  shimmerClass3 : {
    width: '80%',
    height: 10,
    marginTop: 5,
    borderWidth: 0,
    borderRadius: 5,
    marginHorizontal: '3%',
    borderColor: Color.transparent,
  },
  shimmerClass4 : {
    width: '40%',
    height: 10,
    marginTop: 5,
    borderWidth: 0,
    borderRadius: 5,
    marginHorizontal: '3%',
    borderColor: Color.transparent,
  },
  shimmerClass5 : {
    width: '40%',
    height: 18,
    marginTop: 10,
    borderWidth: 0,
    borderRadius: 5,
    marginHorizontal: '3%',
    borderColor: Color.transparent,
  },
  shimmerStoryPage : {
    padding:0,
    width: 296,
    height: 227,
    borderRadius: 20,
    marginVertical: 8,
    marginHorizontal: 12,
    backgroundColor : Color.white,
  },
  shimmerStoryPage1 : {
    width: '100%',
    height: 120,
    borderWidth: 0,
    shadowRadius: 2.22,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowOffset: { width: 0, height: 1 },
  },
  shimmerStoryPage2 : {
    height: 10,
    marginTop: 6,
    borderWidth: 0,
    borderRadius: 5,
    marginHorizontal: '3%',
    borderColor: Color.transparent,
  },
  shimmerStoryPage3 : {
    height: 10,
    marginTop: 6,
    borderWidth: 0,
    borderRadius: 5,
    marginHorizontal: '3%',
    borderColor: Color.transparent,
  },
  shimmerStoryPage4 : {
    height: 10,
    marginTop: 6,
    borderWidth: 0,
    borderRadius: 5,
    marginHorizontal: '3%',
    borderColor: Color.transparent,
  },
  shimmerStoryPage5 : {
    height: 24,
    left: '63%',
    width: '30%',
    marginTop: 15,
    marginHorizontal: '3%',
    borderWidth: 0,
    borderRadius: 5,
    borderColor: Color.transparent,
  },
  containerImg : {
    width: 110,
    height: 102,
    marginRight: 10,
    borderRadius: 20,
  },
  containerTxt : {
    marginLeft: 10,
  },
  ViewTitle : {
    width: 170,
    height: 20,
    borderRadius: 4,
  },
  ViewTxt1 : {
    width: 150,
    height: 15,
    marginTop: 6,
    borderRadius: 4,
  },
  ViewTxt2 : {
    width: 150,
    height: 12,
    marginTop: 24,
    borderRadius: 4,
  },
  ViewTxt3 : {
    width: 160,
    height: 12,
    marginTop: 6,
    borderRadius: 4,
  }
})

export { styles }