const TRANSACT_ALL_REQ = 'TRANSACT_ALL_REQ'
const TRANSACT_ALL_SUCC = 'TRANSACT_ALL_SUCC'
const TRANSACT_ALL_FAIL = 'TRANSACT_ALL_FAIL'
const TRANSACT_ALL_SCROLL = 'TRANSACT_ALL_SCROLL'

const TRANSACT_ACCEPT_REQ = 'TRANSACT_ACCEPT_REQ'
const TRANSACT_ACCEPT_SUCC = 'TRANSACT_ACCEPT_SUCC'
const TRANSACT_ACCEPT_FAIL = 'TRANSACT_ACCEPT_FAIL'
const TRANSACT_ACCEPT_SCROLL = 'TRANSACT_ACCEPT_SCROLL'

const TRANSACT_DECLINE_REQ = 'TRANSACT_DECLINE_REQ'
const TRANSACT_DECLINE_SUCC = 'TRANSACT_DECLINE_SUCC'
const TRANSACT_DECLINE_FAIL = 'TRANSACT_DECLINE_FAIL'
const TRANSACT_DECLINE_SCROLL = 'TRANSACT_DECLINE_SCROLL'

const TRANSACT_USER_LIST_REQ = 'TRANSACT_USER_LIST_REQ'
const TRANSACT_USER_LIST_SUCC = 'TRANSACT_USER_LIST_SUCC'
const TRANSACT_USER_LIST_FAIL = 'TRANSACT_USER_LIST_FAIL'
const TRANSACT_USER_LOAD_SCROLL = 'TRANSACT_USER_LOAD_SCROLL'

export {
  TRANSACT_ALL_REQ,
  TRANSACT_ALL_SUCC,
  TRANSACT_ALL_FAIL,
  TRANSACT_ALL_SCROLL,
  TRANSACT_ACCEPT_REQ,
  TRANSACT_ACCEPT_SUCC,
  TRANSACT_ACCEPT_FAIL,
  TRANSACT_ACCEPT_SCROLL,
  TRANSACT_DECLINE_REQ,
  TRANSACT_DECLINE_SUCC,
  TRANSACT_DECLINE_FAIL,
  TRANSACT_DECLINE_SCROLL,
  TRANSACT_USER_LIST_REQ,
  TRANSACT_USER_LIST_SUCC,
  TRANSACT_USER_LIST_FAIL,
  TRANSACT_USER_LOAD_SCROLL,
}