import { Home, HomeSearch } from './home'
import { Profile, ProfileEdit } from './profile'
import { Alquran, AlquranDetail } from './alquran'
import { Promotion, PromotionDetail } from './promotion'

import {
  Transaction,
  TransactionMethod,
  TransactionInfo,
  TransactionConfirm,
  TransactionUpload,
} from './transaction'
import {
  AdminUser,
  AdminDashboard,
  AdminInstructor,
  AdminProfileAll,
  AdminTransaction,
  AdminProfileEdit,
  AdminProfileInstructor,
} from './admin'
import {
  InstructorJob,
  InstructorTask,
  InstructorProfile,
  InstructorDashboard,
  InstructorTaskDetail,
  InstructorProfileEdit,
} from './instructor'

import { InspiratifStory, InspiratifStoryDetail } from './story'
import { 
  ClassExam, 
  ClassUser,
  ClassTrial, 
  ClassDetail, 
  ClassMeeting,
  ClassLearning, 
  ClassPreference,
  ClassListMentor,
  ClassExamDirect, 
  ClassUserDirect,
  ClassTrialDirect, 
  ClassDetailDirect, 
  ClassLearningDirect, 
  ClassInstructorProfile, 
} from './class'
import { Helps, AboutUs, ContactUs, TermCondition, PrivacyPolice } from './setting'
import { Login, Register, Introduction, CheckEmail, Consultation, ConsultationDetail, UserVerify, UserVerifyPassword, ConfirmPassword, EditPassword } from './user'


export {
  Home,
  Helps,
  Login,
  AboutUs,
  Alquran,
  Profile,
  Register,
  ClassExam,
  Promotion,
  AdminUser,
  ContactUs,
  ClassUser,
  ClassTrial,
  HomeSearch,
  CheckEmail,
  UserVerify,
  ClassDetail,
  ProfileEdit,
  Transaction,
  Introduction,
  Consultation,
  ClassMeeting,
  EditPassword,
  InstructorJob,
  TermCondition,
  PrivacyPolice,
  AlquranDetail,
  ClassLearning,
  AdminDashboard,
  InstructorTask,
  ClassPreference,
  AdminProfileAll,
  PromotionDetail,
  ClassListMentor,
  InspiratifStory,
  AdminInstructor,
  ConfirmPassword,
  TransactionInfo,
  ClassExamDirect, 
  ClassUserDirect,
  AdminTransaction,
  AdminProfileEdit,
  ClassTrialDirect, 
  ClassDetailDirect, 
  TransactionUpload,
  InstructorProfile,
  TransactionMethod,
  ConsultationDetail,
  UserVerifyPassword,
  TransactionConfirm,
  ClassLearningDirect,  
  InstructorDashboard,
  InstructorTaskDetail,
  InspiratifStoryDetail,
  InstructorProfileEdit,
  ClassInstructorProfile,
  AdminProfileInstructor,
}
