import { Home, HomeSearch } from './home'
import { Profile, ProfileEdit } from './profile'
import { Alquran, AlquranDetail } from './alquran'
import { Promotion, PromotionDetail } from './promotion'

import {
  Transaction,
  TransactionMethod,
  TransactionInfo,
  TransactionConfirm,
  TransactionUpload,
} from './transaction'
import {
  AdminUser,
  AdminDashboard,
  AdminInstructor,
  AdminProfileAll,
  AdminTransaction,
  AdminProfileEdit,
  AdminProfileInstructor,
} from './admin'
import {
  InstructorJob,
  InstructorTask,
  InstructorProfile,
  InstructorDashboard,
  InstructorTaskDetail,
  InstructorProfileEdit,
} from './instructor'

import {
  ClassDetailACC,
  ClassFormOtherACC, 
  ClassFormConfirmACC,
  ClassFormPersonalACC,
} from './acc'

import { InspiratifStory, InspiratifStoryDetail } from './story'
import { 
  ClassExam, 
  ClassUser,
  ClassTrial, 
  ClassDetail, 
  ClassMeeting,
  ClassLearning, 
  ClassPreference,
  ClassListMentor,
  ClassExamDirect, 
  ClassUserDirect,
  ClassTrialDirect, 
  ClassReviewMentor,
  ClassDetailDirect, 
  ClassLearningDirect, 
  ClassInstructorProfile, 
} from './class'
import {
  ClassListQuran,
  ClassDetailQuran,
  ClassListMentorQuran,
  TransactionInfoQuran,
  TransactionMethodQuran,
  TransactionUploadQuran,
  ClassProfileMentorQuran,
  TransactionConfirmQuran,
} from './class-alquran'
import { Helps, AboutUs, ContactUs, TermCondition, PrivacyPolice } from './setting'
import { 
  Login, 
  Register, 
  CheckEmail, 
  UserVerify, 
  Introduction, 
  Consultation, 
  EditPassword,
  ConfirmPassword, 
  UserNotification, 
  ConsultationDetail, 
  UserVerifyPassword, 
} from './user'

import { 
  EventClassIntens,
  EventClassIntensConfirm
} from './event'

export {
  Home,
  Helps,
  Login,
  AboutUs,
  Alquran,
  Profile,
  Register,
  ClassExam,
  Promotion,
  AdminUser,
  ContactUs,
  ClassUser,
  ClassTrial,
  HomeSearch,
  CheckEmail,
  UserVerify,
  ClassDetail,
  ProfileEdit,
  Transaction,
  Introduction,
  Consultation,
  ClassMeeting,
  EditPassword,
  InstructorJob,
  TermCondition,
  PrivacyPolice,
  AlquranDetail,
  ClassLearning,
  ClassDetailACC,
  ClassListQuran,
  AdminDashboard,
  InstructorTask,
  ClassPreference,
  AdminProfileAll,
  PromotionDetail,
  ClassListMentor,
  InspiratifStory,
  AdminInstructor,
  ConfirmPassword,
  TransactionInfo,
  EventClassIntens,
  ClassExamDirect, 
  ClassUserDirect,
  AdminTransaction,
  AdminProfileEdit,
  ClassDetailQuran,
  UserNotification,
  ClassTrialDirect, 
  ClassDetailDirect, 
  ClassFormOtherACC,
  ClassReviewMentor,
  TransactionUpload,
  InstructorProfile,
  TransactionMethod,
  ConsultationDetail,
  UserVerifyPassword,
  TransactionConfirm,
  ClassFormConfirmACC,
  ClassLearningDirect,  
  InstructorDashboard,
  TransactionInfoQuran,
  ClassFormPersonalACC,
  ClassListMentorQuran,
  InstructorTaskDetail,
  InspiratifStoryDetail,
  InstructorProfileEdit,
  ClassInstructorProfile,
  TransactionMethodQuran,
  AdminProfileInstructor,
  TransactionUploadQuran,
  TransactionConfirmQuran,
  EventClassIntensConfirm,
  ClassProfileMentorQuran,
}
