const CONSUL_ALL_REQ = 'CONSUL_ALL_REQ'
const CONSUL_ALL_SUCC = 'CONSUL_ALL_SUCC'
const CONSUL_ALL_FAIL = 'CONSUL_ALL_FAIL'
const CONSUL_ALL_SCROLL = 'CONSUL_ALL_SCROLL'

const CONSUL_ACCEPT_REQ = 'CONSUL_ACCEPT_REQ'
const CONSUL_ACCEPT_SUCC = 'CONSUL_ACCEPT_SUCC'
const CONSUL_ACCEPT_FAIL = 'CONSUL_ACCEPT_FAIL'
const CONSUL_ACCEPT_SCROLL = 'CONSUL_ACCEPT_SCROLL'

const CONSUL_DECLINE_REQ = 'CONSUL_DECLINE_REQ'
const CONSUL_DECLINE_SUCC = 'CONSUL_DECLINE_SUCC'
const CONSUL_DECLINE_FAIL = 'CONSUL_DECLINE_FAIL'
const CONSUL_DECLINE_SCROLL = 'CONSUL_DECLINE_SCROLL'

const CONSUL_MENTOR_LIST_REQ = 'CONSUL_MENTOR_LIST_REQ'
const CONSUL_MENTOR_LIST_SUCC = 'CONSUL_MENTOR_LIST_SUCC'
const CONSUL_MENTOR_LIST_FAIL = 'CONSUL_MENTOR_LIST_FAIL'
const CONSUL_MENTOR_LOAD_SCROLL = 'CONSUL_MENTOR_LOAD_SCROLL'

export {
  CONSUL_ALL_REQ,
  CONSUL_ALL_SUCC,
  CONSUL_ALL_FAIL,
  CONSUL_ALL_SCROLL,
  CONSUL_ACCEPT_REQ,
  CONSUL_ACCEPT_SUCC,
  CONSUL_ACCEPT_FAIL,
  CONSUL_ACCEPT_SCROLL,
  CONSUL_DECLINE_REQ,
  CONSUL_DECLINE_SUCC,
  CONSUL_DECLINE_FAIL,
  CONSUL_DECLINE_SCROLL,
  CONSUL_MENTOR_LIST_REQ,
  CONSUL_MENTOR_LIST_SUCC,
  CONSUL_MENTOR_LIST_FAIL,
  CONSUL_MENTOR_LOAD_SCROLL,
}