const STORY_LIST_REQ = 'STORY_LIST_REQ'
const STORY_LIST_SUCC = 'STORY_LIST_SUCC'
const STORY_LIST_FAIL = 'STORY_LIST_FAIL'
const STORY_LOAD_SCROLL = 'STORY_LOAD_SCROLL'

export {
  STORY_LIST_REQ,
  STORY_LIST_SUCC,
  STORY_LIST_FAIL,
  STORY_LOAD_SCROLL,
}