const MENTOR_REQ = 'MENTOR_REQ'
const MENTOR_SUCC = 'MENTOR_SUCC'
const MENTOR_FAIL = 'MENTOR_FAIL'
const MENTOR_LOAD_SCROLL = 'MENTOR_LOAD_SCROLL'

export {
  MENTOR_REQ,
  MENTOR_SUCC,
  MENTOR_FAIL,
  MENTOR_LOAD_SCROLL,
}