const USER_CLASS_LIST_REQ = 'USER_CLASS_LIST_REQ'
const USER_CLASS_LIST_SUCC = 'USER_CLASS_LIST_SUCC'
const USER_CLASS_LIST_FAIL = 'USER_CLASS_LIST_FAIL'
const USER_CLASS_DETAIL_REQ = 'USER_CLASS_DETAIL_REQ'
const USER_CLASS_LOAD_SCROLL = 'USER_CLASS_LOAD_SCROLL'

export {
  USER_CLASS_LIST_REQ,
  USER_CLASS_LIST_SUCC,
  USER_CLASS_LIST_FAIL,
  USER_CLASS_DETAIL_REQ,
  USER_CLASS_LOAD_SCROLL,
}