import {StyleSheet} from 'react-native'
import {FontType} from '../../../assets'

const styles = StyleSheet.create({
    containerView : {
        flex: 1,
        backgroundColor: '#9956B3',
        fontFamily: FontType.regular,
    },
    containerHeader : {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    containerTextHeader : {
        fontSize: 18,
        color: '#fff',
        marginTop: '5%',
        marginLeft: '5%',
    },
    containerButtonFilter : {
        marginRight: '2%',
        top: '25%',
    },
    containerTouchFilter : {
        width: 100,
    },
    containerViewClass : {
        zIndex: 1,
        width: '90%',
        opacity: 0.8,
        height: '50%',
        padding: '5%',
        marginTop: '5%',
        borderRadius: 25,
        alignItems: 'center',
        marginHorizontal: '5%',
        backgroundColor: '#722A90',
    },
    containerTextClass : {
        fontSize: 28,
        color: '#fff',
        fontWeight: 'bold',
        marginVertical: 10,
    },
    containerChildTextClass : {
        fontSize: 16,
        color: '#fff',
    },
    containerChildTextClass2 : {
        fontSize: 16,
        color: '#fff',
        fontWeight: 'bold',
    },
    containerClassProgress : {
        marginTop: 20,
        paddingTop: '3%',
        paddingBottom: '8%',
        flexDirection: 'row',
        marginHorizontal: '5%',
        paddingHorizontal: '7%',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        backgroundColor: '#9956B3',
        justifyContent: 'space-between',
    },
    containerIconProgress : {
        paddingTop: '4%',
        marginRight: '5%',
        paddingBottom: '2%',
        flexDirection: 'row',
        paddingHorizontal: '7%',
        justifyContent: 'space-between',
    },
    ImageClass : {
        width: 100,
        height: 100,
        marginTop: 5,
    },
    TextClass : {   
        width: '60%',
        fontSize: 14,
        color: '#fff',
        fontFamily: FontType.regular,   
    },
    ButtonTextClass : {
        color:'#fff', 
        fontSize: 16, 
        marginLeft: '5%',
        marginTop: '-8%',
        fontWeight: 'bold',
        alignSelf: 'center', 
        fontFamily: FontType.regular,
    },
    ButtonClass : {
        width: 100,
        height: 50,
        borderRadius: 20,
        marginRight: '5%',
        backgroundColor: '#6e248d',
    },
    ButtonClassNew : {
        width: 130,
        height: 50,
        borderRadius: 20,
        marginRight: '5%',
        backgroundColor: '#6e248d',
    },
    containerReview : {
        zIndex: 100,
        width: '90%',
        height: 'auto',
        borderRadius: 30,
        marginBottom: '10%',
        paddingVertical: '5%',
        marginHorizontal: '5%',
        paddingHorizontal: '5%',
        backgroundColor: '#FEF5FF',
    },
    containerClassReview : {
        display: 'flex',
        paddingVertical: 1,
        flexDirection: 'row',
    },
    TextHeaderReview : {
        fontSize: 16,
        marginTop: 5,
    },
    ButtonClassReview : {
        height: 40,
        fontSize: 12,
        color: '#fff',
        width: 'auto',
        marginTop: 10,
        marginRight: 10,
        borderRadius: 20,
        paddingVertical: 10,
        paddingHorizontal: 15,
        backgroundColor: '#6e248d',
    },
    textarea: {
        height: 170,
        fontSize: 14,
        elevation: 3,
        color: '#333',
        marginTop: '5%',
        borderRadius: 10,
        shadowRadius: 3.84,
        shadowOpacity: 0.25,
        shadowColor: "#000",
        backgroundColor: '#fff',
        textAlignVertical: 'top', 
        shadowOffset: {width: 0,height: 2,},   
    },
    containerRating : {
        marginTop: '5%',    
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    customRatingBarStyle: {
        marginTop: 10,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    starImageStyle: {
        width: 30,
        height: 30,    
    },
})

export {styles}