import { StyleSheet, Dimensions } from 'react-native'
import { Color, FontSize, FontType } from '../../../assets'

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerFullscreen: {
    width: '100%',
    height: '100%',
  },
  containerView : {
    flex: 2.4,
    backgroundColor: '#9956B3',
    fontFamily: FontType.regular,
  },
  containerHeader : {
    height: '10%',
    backgroundColor: '#9956B3',
  },
  buttonBack : {
    top: 0,
    left: 0,
    zIndex : 10,
    position: 'absolute',
    backgroundColor:'yellow'
  },
  containerTouchFilter : {
    width: 100,
  },
  containerClassProgress : {
    marginTop: 20,
    paddingTop: '3%',
    paddingBottom: '8%',
    flexDirection: 'row',
    marginHorizontal: '5%',
    paddingHorizontal: '7%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#9956B3',
    justifyContent: 'space-between',
  },
  containerIconProgress : {
    flexDirection: 'row',
    paddingVertical: '3%',
    paddingHorizontal: '7%',
    justifyContent: 'space-between',
  },
  ImageClass : {
    width: 100,
    height: 100,
    marginTop: 5,
  },
  TextClass : {
    width: '60%',
    fontSize: 16,
    color: '#fff',
    marginLeft: '3%',
    marginTop: '-5%',
    alignSelf: 'center',
    fontFamily: FontType.regular,
  },
  ButtonTextClass : {
    fontSize: 18,
    color:'#fff',
    marginTop: '-8%',
    marginLeft: '12%',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  ButtonClass : {
    width: 100,
    height: 50,
    paddingTop: 15,
    borderRadius: 20,
    marginRight: '5%',
    backgroundColor: '#6e248d',
  },
  ButtonClassNew : {
    width: 130,
    height: 50,
    paddingTop: 15,
    borderRadius: 20,
    marginRight: '5%',
    backgroundColor: '#6e248d',
  },
  containerParentKelas : {
    backgroundColor: Color.softPink,
  },
  containerMenuDesc : {
    width: '100%',
    paddingTop: 20,
    paddingBottom: 5,
    paddingHorizontal: 18,
    backgroundColor: Color.softPink,
  },
  containerTextTitle : {
    lineHeight:18,
    paddingVertical: 5,
    fontFamily: FontType.bold,
    fontSize: FontSize.mediumLarge,
  },
  containerTextCategory : {
    marginTop:2,
    marginBottom:10,
    fontFamily: FontType.regular,
    fontSize: FontSize.smallMedium,
  },
  containerTextDesc : {
    lineHeight:15,
    fontFamily: FontType.regular,
    fontSize: FontSize.extraSmall,
  },
  containerParentReview : {
    flexDirection: 'row',
    marginVertical: '3%',
  },
  containerReviewUser : {
    flexDirection: 'row',
    alignContent: 'space-between',
  },
  textRating : {
    marginLeft: 10,
    fontFamily: FontType.regular,
    fontSize: FontSize.extraSmall,
  },
  containerMenuDetail : {
    height: 'auto',
    paddingBottom: 5,
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  containerTitleContent : {
    marginTop:10,
    color: Color.black,
    marginHorizontal:16,
    fontSize: FontSize.medium,
    fontFamily: FontType.regular,
  },
  containerTextHeaderDetail : {
    borderTopWidth: 1,
    borderBottomWidth:1,
    backgroundColor:'#FFF',
    borderColor: '#e6e6e6',
  },
  containerTextDetail : {
    borderTopWidth: 1,
    borderColor: '#e6e6e6',
    backgroundColor:'#fef5ff',
  },
  videoContainerStyle: {
    width: '100%',
    height: '100%',
    alignSelf: 'center',
    backgroundColor: Color.softPink,
  },
  videoFullscreenContainerStyle: {
    width: '100%',
    height: '100%',
    backgroundColor: 'black',
  },
  videoStyle: {
    width: '100%',
    height: '100%',
  },
  videoFullscreenStyle: {
    width: '100%',
    height: '100%',
  },
  controllerStyle: {
    width: '100%',
    height: '100%',
    alignSelf: 'center',
    position: 'absolute',
    backgroundColor: '#000000c4',
    justifyContent: 'space-between',
  },
  controllerFullscreenStyle: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    position: 'absolute',
    backgroundColor: '#000000c4',
    justifyContent: 'space-between',
  },
  textStyle: {
    color: '#000',
    marginLeft: 10,
    textAlign: 'center',
    fontFamily: FontType.regular,
    fontSize: FontSize.extraSmall,
  },
  customRatingBarStyle: {
    marginLeft: '10%',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  starImageStyle: {
    width: 12,
    height: 12,
    marginRight:2,
  },
  containerConsul : {
    width: '100%',
    borderRadius: 20,
    paddingVertical : 0,
    paddingHorizontal: 25,
    backgroundColor: '#9741ba',
  },
  containerItemConsul : {
    height : 100,
    width: '100%',
    paddingVertical : 0,
    paddingHorizontal: 25,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius : 20,
    backgroundColor: Color.white,
  },
  textConsul : {
    color: '#fff',
    marginLeft: '5%',
    marginVertical: 5,
    fontFamily: FontType.bold,
    fontSize: FontSize.smallMedium,
  },
  textRegular: {
    fontSize: 13.5,
    color: Color.black,
    fontFamily: FontType.regular,
  },
  textExam: {
    right : 7,
    fontSize: 11,
    color: '#9741ba',
    alignSelf : 'center',
    fontFamily: FontType.regular,
  },
  containerAccordion: {
    paddingVertical: 0,
    paddingHorizontal: 9,
    borderBottomWidth: 1,
    borderColor: Color.lightGrey,
    backgroundColor: Color.white,
  },
  containerExam : {
    paddingVertical: 5,
    borderTopWidth : 1,
    borderBottomWidth : 1,
    borderColor: Color.lightGrey,
  },
  containerItem: {
    paddingVertical: 4,
    borderBottomWidth: 1,
    paddingHorizontal: 15,
    borderColor: Color.lightGrey,
    backgroundColor : Color.softPink
  },
  iconPlay : {
    marginRight:5,
    alignSelf:'center',
  },
  textDuration : {
    alignSelf:'center',
    fontSize: 10,
    fontFamily: FontType.regular,
  },
  containerPDF : {
    flex : 1,
    backgroundColor : Color.transactionBgColor,
  },
  containerHeaderPDF : {
    height : 50,
    paddingVertical : 7,
    flexDirection : 'row',
    paddingHorizontal : 10,
    justifyContent: 'space-between',
  },
  buttonBackPDF : {
    width : 'auto',
    marginLeft : -5,
    height : 'auto',
  },
  buttonDownloadPDF : {
    padding : 5,
    elevation : 4,
    width : 'auto',
    height : 'auto',
    borderRadius : 10,
    alignItems : 'center',
    flexDirection : 'row',
    justifyContent : 'center',
    backgroundColor : '#9956B3',
  },
  textDonwload : {
    marginLeft : 3,
    color : Color.white,
    fontSize: FontSize.small,
    fontFamily: FontType.regular,
  },
  textPdf : {
    color : Color.white,
    textAlign : 'left',
    fontFamily: FontType.bold,
    fontSize: FontSize.medium,
  },
  containerTextPdf : {
    flex : 1,
    justifyContent : 'center',
  },
  star : {
    marginRight:1,
  },
  containerRecentJobs: {
    marginBottom:20
  },
  avatarUser: {
    width: 48,
    height: 48,
  },
  textUsername: {
    color: Color.black,
    fontSize: FontSize.medium,
    fontFamily: FontType.bold,
  },
  textMoment: {
    color: Color.black,
    fontSize: FontSize.extraSmall,
    fontFamily: FontType.regular,
  },
  semiBox: {
    height: 12,
    marginLeft: 0,
    marginTop: -12,
    marginRight: 16,
    backgroundColor: Color.white,
  },
  containerChat: {
    marginTop: 0,
    marginLeft: 0,
    paddingLeft: 0,
    marginRight: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    backgroundColor: Color.white,
  },
  containerUserChatItem: {
    width: '75%',
    paddingTop: 4,
    borderWidth: 0,
    paddingLeft: 16,
    paddingRight: 4,
    borderRadius: 20,
    paddingBottom: 16,
    borderTopLeftRadius: 0,
    backgroundColor: Color.softPink,
  },
  containerUserSound: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  btnPlayVoice: {
    marginRight: 8,
  },
  textSoundDuration: {
    color: Color.black,
    marginHorizontal: 8,
    fontSize: FontSize.medium,
    fontFamily: FontType.regular,
  },
  containerAvatarUser: {
    flex: 1,
    height: 44,
    alignItems: 'flex-end',
  },
  avatarChatInstructor: {
    width: 44,
    height: 44,
  },
  containerUserDesc: {
    paddingLeft: 10,
  },
  textDesc: {
    marginTop: 2,
    color: Color.black,
    fontFamily: FontType.bold,
    fontSize: FontSize.smallest,
  },
  textUserDesc: {
    marginTop: 2,
    color: Color.black,
    fontSize: FontSize.medium,
    fontFamily: FontType.regular,
  },
  textTime: {
    marginTop: 4,
    marginRight: 16,
    textAlign: 'right',
    color: Color.black,
    fontSize: FontSize.medium,
    fontFamily: FontType.regular,
  },
  containerConfirm: {
    marginTop: 8,
    marginRight: 16,
    marginBottom: -8,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  containerChatInstructor: {
    padding: 4,
    width: '75%',
    borderWidth: 0,
    borderRadius: 20,
    alignSelf: 'flex-end',
    borderTopRightRadius: 0,
    backgroundColor: Color.softPink,
  },
  containerInstructorHeader: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  textInstructorName: {
    marginLeft: 8,
    color: Color.black,
    fontFamily: FontType.bold,
    fontSize: FontSize.smallest,
  },
  containerInstructorSound: {
    marginTop: 4,
    marginLeft: 8,
    flexDirection: 'row',
  },
  textInstructorDesc: {
    color: Color.black,
    fontSize: FontSize.medium,
    fontFamily: FontType.regular,
  },
  containerChatInstructorFull: {
    padding: 4,
    width: '75%',
    borderWidth: 0,
    borderRadius: 20,
    alignSelf: 'flex-end',
    borderTopRightRadius: 0,
    backgroundColor: Color.bgColorPurple,
  },
  containerInstructorDesc: {
    marginTop: 4,
    paddingLeft: 20,
    marginBottom: 4,
  },
  textInstructorNameWhite: {
    marginLeft: 8,
    color: Color.white,
    fontFamily: FontType.bold,
    fontSize: FontSize.smallest,
  },
  textSoundDurationWhite: {
    color: Color.white,
    marginHorizontal: 8,
    fontSize: FontSize.medium,
    fontFamily: FontType.regular,
  },
  textDescWhite: {
    marginTop: 2,
    color: Color.white,
    fontFamily: FontType.bold,
    fontSize: FontSize.smallest,
  },
  textInstructorDescWhite: {
    color: Color.white,
    fontSize: FontSize.medium,
    fontFamily: FontType.regular,
  },
  textTimeWhite: {
    marginTop: 4,
    marginRight: 16,
    textAlign: 'right',
    color: Color.white,
    fontSize: FontSize.medium,
    fontFamily: FontType.regular,
  },
  containerTextInput: {
    flexDirection: 'row',
  },
  textInput: {
    width: '75%',
    marginLeft: 20,
    marginRight: 16,
    paddingLeft: 24,
    borderRadius: 28,
    marginVertical: 16,
    backgroundColor: Color.softPink,
  },
  containerSend: {
    height: 48,
    width: '160%',
    marginLeft: 4,
    borderRadius: 20,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
})

export { styles }