const QURAN_LIST_REQ = 'QURAN_LIST_REQ'
const QURAN_LIST_SUCC = 'QURAN_LIST_SUCC'
const QURAN_LIST_FAIL = 'QURAN_LIST_FAIL'
const QURAN_DETAIL_REQ = 'QURAN_DETAIL_REQ'
const QURAN_DETAIL_SUCC = 'QURAN_DETAIL_SUCC'
const QURAN_DETAIL_FAIL = 'QURAN_DETAIL_FAIL'

export {
  QURAN_LIST_REQ,
  QURAN_LIST_SUCC,
  QURAN_LIST_FAIL,
  QURAN_DETAIL_REQ,
  QURAN_DETAIL_SUCC,
  QURAN_DETAIL_FAIL
}