import {
  QURAN_LIST_REQ,
  QURAN_LIST_SUCC,
  QURAN_LIST_FAIL,
  QURAN_DETAIL_REQ,
  QURAN_DETAIL_SUCC,
  QURAN_DETAIL_FAIL
} from './alquran.action'

export {
  QURAN_LIST_REQ,
  QURAN_LIST_SUCC,
  QURAN_LIST_FAIL,
  QURAN_DETAIL_REQ,
  QURAN_DETAIL_SUCC,
  QURAN_DETAIL_FAIL
}